### ISSUE TITLE
loop_interchange_2 marked as broken

### ISSUE THREAD

**Issue by JonathanHallstrom** [grahamking/perf-ninja-rs#5]
seems perfectly fine to me, i get a 92% speedup switching the `r` and `c` loops for the middle part of the vertical kernel
see [b1956cf](https://github.com/JonathanHallstrom/perf-ninja-rs/commit/b1956cf272ed1822804d5d10ed152b39e3f463e0)

**Comment by JonathanHallstrom** [comment]
goes from 150ms to 12ms for me

**Comment by grahamking** [comment]
Wonderful, thanks. I removed the README saying it's broken.
https://github.com/grahamking/perf-ninja-rs/commit/ebf63228d4610b8b86300373ede063461025cfac
