### ISSUE TITLE
vectorizazion2 lab is using Wrapping(0) instead of Wrapping(0_u16)

### ISSUE THREAD

**Issue by giovannicuccu** [grahamking/perf-ninja-rs#6]
Hi,
   I'm trying to solve the performance ninja labs and I think there is a bug n vectorization_2
the source code is using `Wrapping(0)` which is a `Wrapping` of u32 and so overflow should never happen if you sum 64k u16 values.
In the original [source code](https://github.com/dendibakh/perf-ninja/blob/main/labs/core_bound/vectorization_2/solution.cpp)
acc is defined as `uint16_t`.
The correct code should use `Wrapping(0_u16)`
Can I submit a pull request with the fix ?

**Comment by grahamking** [comment]
That's a very good point. Yes please!

**Comment by giovannicuccu** [comment]
Hi,
  upon closer inspection it turns out that I was wrong. It appears that the actual type of `Wrapping(0)` is inferred not by the initial declaration, but by the operations performed on it. Thus, the inferred type is u16. I should have written a unit test instead of simply guessing.

**Comment by grahamking** [comment]
I'm pretty sure Rust infers the type based on the return type of the function. `acc.0` is the inner value of `Wrapping`. The function returns a `u16`, ergo that initial `0` must be a `u16`.
